# Generated by Django 2.2.7 on 2020-01-05 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='pass_word',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='user_name',
            new_name='username',
        ),
    ]
