# Generated by Django 2.2.7 on 2019-12-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognize', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='pic',
            field=models.ImageField(default=1, max_length=255, upload_to=''),
            preserve_default=False,
        ),
    ]
