# Generated by Django 2.2.7 on 2020-01-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='STAFF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(max_length=255, upload_to='')),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('age', models.CharField(max_length=3)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=6)),
                ('nationality', models.CharField(max_length=255)),
                ('state_of_origin', models.CharField(max_length=255)),
                ('lga_origin', models.CharField(max_length=255)),
                ('marital_status', models.CharField(max_length=255)),
                ('profession', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=500)),
                ('phone_number', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_registration', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='STUDENTS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(max_length=255, upload_to='')),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('age', models.CharField(max_length=3)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=6)),
                ('nationality', models.CharField(max_length=255)),
                ('state_of_origin', models.CharField(max_length=255)),
                ('lga_origin', models.CharField(max_length=255)),
                ('marital_status', models.CharField(max_length=255)),
                ('jamb_number', models.CharField(max_length=10)),
                ('college', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=500)),
                ('level', models.CharField(max_length=4)),
                ('matric_number', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=500)),
                ('phone_number', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('parent_name', models.CharField(max_length=255)),
                ('parent_email', models.EmailField(max_length=254)),
                ('parent_phone', models.CharField(max_length=11)),
                ('date_of_registration', models.DateField()),
            ],
        ),
    ]
